### ISSUE TITLE
Missing Gumps PandoraUO

### ISSUE THREAD

**Issue by crameep** [ClassicUO/ClassicUO#1045]
Hey this client is awesome, loving the features, is there anyways to troubleshoot missing gumps? like when i Open the soulforge on pandora, i get no gump in debug mode it shows an outline for an invisible gump? same for an item called master runebook. also they have a toolbar, with an interface to move it, it doesn't seem to work right either, when I click the move button the grid comes up and it moves AFTER I relaunch the client, on normal client it moves without restarting. I can try and record this if it helps, or whatever you need me to do to help troubleshoot, just let me know.

**Comment by andreakarasho** [comment]
yes do a rec please

**Comment by crameep** [comment]
Ok, done, first one is normal updated UO client second is ClassicUO Client. ClassicUO is spoiling me, hope we can get it nocked out whatever I need to do to help, just let me know.

[Video](https://youtu.be/61jHHijzNMI)

**Comment by andreakarasho** [comment]
Hi, i fixed the gump positioning, but i don't have other items to test. Write me on discord

**Comment by andreakarasho** [comment]
fixed

**Comment by SkylerPixel** [comment]
I seem to be having the same issue with the master runebook on PandoraUO, was there ever a fix for this?

**Comment by crameep** [comment]
This issue is back, i think your fix for it got rolled back a bit at some point.
