### ISSUE TITLE
Taking screenshots of CUO with Razor no longer works

### ISSUE THREAD

**Issue by PaxRomain** [ClassicUO/ClassicUO#1159]
The razor plugin is no longer able to take screenshots of CUO. As nothing changed with razor, this appears to be something that changed in CUO.

**Comment by BlackTeaOutlands** [comment]
+1 Please fix! Death screenshots are great I want them

**Comment by andreakarasho** [comment]
not a cuo issue.
Working with Quick to find a workaround

**Comment by andreakarasho** [comment]
actually was an hidden cuo issue [when using a driver different from openGL].
Fixed

**Comment by ghost** [comment]
This is still an issue for me.  None of the Razor screenshot tab functionality has worked for me on Outlands since ~July. Is there anything that can be done here?
