### ISSUE TITLE
Skip empty corpses (Auto Open Corpses) does not work

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#1163]
Using the **Skip empty corpses** option no longer works, and the client constantly opens corpses that are empty.

![2020-07-26_00-18-20](https://user-images.githubusercontent.com/1727541/88467371-a84a8280-ced6-11ea-94eb-ee4005098860.gif)

**Comment by andreakarasho** [comment]
fixed

**Comment by Hezkore** [comment]
This is still an issue with the normal container gump.
The original implementation https://github.com/andreakarasho/ClassicUO/pull/841 that I provided back in 2019 worked by hiding the container gump for corpses that were auto opened.
They remained hidden until the container had at least one item inside of it, or if they player went out of reach.
Corpses that were manually opened always displayed, even if they were empty.

**Comment by andreakarasho** [comment]
fixed!

**Comment by Hezkore** [comment]
Almost fixed! :)
The container is now always hidden if it doesn't contain something, not only when it's auto opened.
For example if you the loot the last item in a container it will auto close the container.
_(should be its own option honestly - **Auto Close Empty Corpse Containers**)_
And if you try to open a corpse manually it doesn't open if the container is empty, which should never happen.

**Comment by andreakarasho** [comment]
should be ok now :D
