### ISSUE TITLE
Scrollbars behave oddly

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#1172]
The scrollbars either don't work, or the offset is wrong while dragging.

![2020-08-10_13-54-05](https://user-images.githubusercontent.com/1727541/89780095-09966680-db11-11ea-9a79-1bb7112d467c.gif)

**Comment by andreakarasho** [comment]
fixed thanks!

ps: welcome back

**Comment by Hezkore** [comment]
Thanks.

There's however still an issue with some scrollbars not working correctly.
I can't drag the scrollbar in the **Combat-Spells** view for example.
My guess is that it occurs when the scrollable length is low.

![2020-08-10_16-41-28](https://user-images.githubusercontent.com/1727541/89795170-5df91080-db28-11ea-8a09-a2b835557c78.gif)

Also the scrollbar in my **Macros** view isn't draggable unless I move the mouse cursor extremely fast.

![2020-08-10_16-43-44](https://user-images.githubusercontent.com/1727541/89795498-c34d0180-db28-11ea-9b7b-30accfe685ba.gif)

**Comment by andreakarasho** [comment]
done
