### ISSUE TITLE
Circle of transparency not working right in CUO

### ISSUE THREAD

**Issue by TyrAntilles** [ClassicUO/ClassicUO#457]
Greetings. I just encountered a big problem with CUO trying to unlock some chests while stealthing in dungeons. Is possible that I do not see something obvious, but I tried everything I could.

If the chest is covered by an obstacle and I use circle of transparency I am still unable to click the chest from under that obstacle even if I see it just fine. Plus, if I try to use CTRL+SHIFT, chests show no label as they do in the 2D client.
These issues effectively render some chests unopenable on CUO.

I see a version of this problem was reported earlier here: https://github.com/andreakarasho/ClassicUO/issues/244

Attached are some screenshots that illustrates the problem.

[CUO cannot open chests with circle of transparency.zip](https://github.com/andreakarasho/ClassicUO/files/3125361/CUO.cannot.open.chests.with.circle.of.transparency.zip)

 - OS: win10x64
 - Version CUO v.Alpha 8 - 0.0.1.8

**Comment by andreakarasho** [comment]
Should be fixed in dev branch, you can download the dev preview from releases page.
I'll wait a feedback :)

**Comment by TyrAntilles** [comment]
To test I used dev preview v.0.0.1.280 (https://github.com/andreakarasho/ClassicUO/releases/tag/ClassicUO-dev-preview)

I see no change. I still can't click that trash barrel in the house because it still clicks on "slate roof" and the chests in dungeon are still covered.

![J20190429_190511 circle of transparency](https://user-images.githubusercontent.com/48412376/56910455-4b81d180-6ab3-11e9-84e0-603b9d93a042.jpg)

**Comment by andreakarasho** [comment]
fixed
