### ISSUE TITLE
Boats don't display correctly when moving

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#480]
**Describe the bug**
On UOR at least, when you are in a boat, most of the boat won't move with you.  When you leave the screen and come back, the boat will be together again until you tell it to move.

![image](https://cdn.discordapp.com/attachments/531214935804608515/574079942405652500/2019-05-03_22-47-05.gif)

**Comment by andreakarasho** [comment]
fixed in dev

**Comment by markdwags** [comment]
This bug still exists.  Moving forward works, but when you turn the boat turned out like this.

![image](https://i.imgur.com/e5WsDd6.png)

![image](https://imgur.com/2gQbrEM.gif)

**Comment by markdwags** [comment]
One additional comment. Unable to open the plank via-double click. Nothing happens.

**Comment by andreakarasho** [comment]
re-fixed in dev
