### ISSUE TITLE
CTRL-SHIFT and All-Names not showing names properly

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#564]
Ctrl-shift and all names will not display names or tags on floors that are above you. The proper function is that it displays everything on screen.

**Comment by oroechimaru** [comment]
I noticed it beint an issue at the ice fort on uo outlands starting in late June. You can still see hp bars with the feature enabled however.

**Comment by BlackTeaOutlands** [comment]
I forgot to write in in the OP: All names will not show names of stuff above you either.

**Comment by andreakarasho** [comment]
Ctrl shift should be fixed.
Lemme know

**Comment by BlackTeaOutlands** [comment]
> Ctrl shift should be fixed.
> Lemme know

Ctrl-shift seems to work properly now 👍

All name still not working (although you did not mention fixing that).

**Comment by andreakarasho** [comment]
try all names now pls

**Comment by BlackTeaOutlands** [comment]
> try all names now pls

All names works now (shows people on floors above, at the location I tried).

It does not work the intended way for other reasons however: When you spam all names it only generates one instance of the name tag which won't be refreshed until it fades out. The regular client (and I argue intended way) is that each instance of you pressing all names should generate a new name tag, i.e. you should get the name spam above the targets head. There are a few reasons why the regular way is a better way for it to function. In CUO if you spam all names, you do however get spam of (bonded), (last target), and the players title and so on.

Video here shows how it works in CUO when spamming all-names:
https://imgur.com/PfFQy6n

And here's a video of how it should work:
https://imgur.com/mC7QRI4

**Comment by andreakarasho** [comment]
fixed

**Comment by BlackTeaOutlands** [comment]
All names is broken again, does not display name of mobiles above your position. In the below screenshot there are mutliple vendors ontop of the roof. Also broken at the previous location in the mage shop reported in the original post.

![image](https://user-images.githubusercontent.com/39037141/61916679-bc694600-af49-11e9-8bb4-dcdb57f1e4cd.png) 
![image](https://user-images.githubusercontent.com/39037141/61916683-c12dfa00-af49-11e9-9672-f219da34fa4d.png)
