### ISSUE TITLE
Item Descriptions appear under the cursor instead of over it

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#578]
A) Item text appears under the cursor when you click on an item. This means that your cursor will cover the text. The desired function is that the text appears above the point you clicked on. ** This seems to be specifically when clicking on items while they are inside a container.

![image](https://user-images.githubusercontent.com/39037141/61015773-54353480-a38d-11e9-923a-4d26f680bada.png)

* edit* B) I also noticed that clicking on items while they are on the ground displays the text too far above the cursor. It is hard to take screenshots which includes the cursor but I will add an image here to show what I mean. I am guessing maybe the text spawns above the entire image of the item, disregarding any transparent pixels. But it should only spawn right above the topmost visible pixel.

![image](https://user-images.githubusercontent.com/39037141/61015753-3d8edd80-a38d-11e9-9ae6-c0c66bb82adb.png)

**Comment by andreakarasho** [comment]
Cursor is displayed over all because cuo change the OS cursor when game is focussed.
But you can disable this option in "video" tab, "run cursor in a separate thread".

Lemme know

**Comment by BlackTeaOutlands** [comment]
> Cursor is displayed over all because cuo change the OS cursor when game is focussed.
> But you can disable this option in "video" tab, "run cursor in a separate thread".
> 
> Lemme know

With "run mouse in seperate thread" disabled, I get exactly the same result.

**Comment by andreakarasho** [comment]
The Y offset has been fixed.

About the mouse over issue: 
The rendering order is:  
- world (tiles, mobiles, etc..)
- world text 
- UI (gumps, controls, CURSOR, etc..)

I'dont know if tag it as an issue tbh

**Comment by BlackTeaOutlands** [comment]
Text of items on ground display better now, some are still not quite correct location, for example this house sign (cursor not shown in scrshot, but I click middle of sign and text appears under the cursor): 
![image](https://user-images.githubusercontent.com/39037141/61170075-7c2ac080-a564-11e9-8440-ee3a83e5c79d.png)

Text on items in backpack are not fixed, the text still appears under the cursor. The problem is not the rendering order. Problem is location of the text.  When you click stuff in backpack, you have to move your cursor to read the text. Rendering order would not matter if text is above the cursor.

**Comment by andreakarasho** [comment]
text now appends to the top of items in containers

**Comment by BlackTeaOutlands** [comment]
Item descriptions on (some) tems on the ground are still not displayed in the proper location.

Example, this plant:
![image](https://user-images.githubusercontent.com/39037141/61594975-bc87df80-abf1-11e9-8226-4b7b8fd0da61.png) -> 
![image](https://user-images.githubusercontent.com/39037141/61594987-e0e3bc00-abf1-11e9-9248-b23d9cc4f5cf.png)

House signs:
![image](https://user-images.githubusercontent.com/39037141/61594994-f953d680-abf1-11e9-82f7-069813235186.png)->
![image](https://user-images.githubusercontent.com/39037141/61594999-007ae480-abf2-11e9-87ad-bf578c198c36.png)
