### ISSUE TITLE
Gating to the inside of a house will not remove the roof of the house

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#583]
If you take a gate to the inside of a house, it will not update and remove the roof of the house until you move. This is an issue if you gate with stuff in your cursor for example (overloaded, you can't select a chest to drop your stuff in), or if you for some reason gate into a house and don't want to move. The desired function is obviously that it's updated so the roof vanishes as soon as you enter the house, without the need to move or anything like that first. Picture below as example:

![image](https://user-images.githubusercontent.com/39037141/61082121-1ede2480-a429-11e9-8a34-2590b8adf008.png)

**Comment by owyn-outlands** [comment]
I noticed and reported this as staff teleporting to players in houses.

**Comment by oroechimaru** [comment]
I havn't had that issue in smaller houses. Possibly its no draw tiles?

**Comment by andreakarasho** [comment]
fixed in dev

**Comment by BlackTeaOutlands** [comment]
Not fixed for me, still have this issue. does dev = the latest version I can download?

https://imgur.com/G5fKPsi

**Comment by andreakarasho** [comment]
Tried few times and it works on my side (no outlands).

Make sure you have latest cuo version.
This is the cuo history: https://ci.appveyor.com/project/andreakarasho/classicuo/history
