### ISSUE TITLE
Custom Outlands Special Effects aren't displayed properly

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#584]
There are alot of different special effects on Outlands, custom made animated by putting together existing art and moving it around/hueing it in various ways. I noticed it is often not displayed properly. Often the hue of the art and the direction/angle of it is not taken into account properly. Example below with a creature called a barbed prowler:

How it looks in ClassicUO:
https://imgur.com/YtDfnBM

How it is supposed to look in regular UO:
https://imgur.com/sYL15Fa

Again, not restricted to only this particular effect. For example another guy who does a spit attack will have his effects in the wrong hue (blue - they should be pink):
https://imgur.com/WjzMXEN

Also on a side note I noticed the corpse graphic of a creature called "cave gorger" is not correct, in CUO it displays a skeleton, while in regular UO it displays something that looks more like the original creature:
![image](https://user-images.githubusercontent.com/39037141/61126106-dfa4e780-a4ab-11e9-97a4-89003fe3cb5c.png)

**Comment by BlackTeaOutlands** [comment]
Re: The Cave Gorger, can't reproduce it, don't know why that one corpse looked like a skeleton. I'll look into it more.

**Comment by andreakarasho** [comment]
I need the graphic to identify that mob (alive)

**Comment by BlackTeaOutlands** [comment]
This is the cave gorger graphic:
![image](https://user-images.githubusercontent.com/39037141/61162351-77382380-a508-11e9-8307-8df93c1f259f.png)

Barbed prowler graphic (with the special effect in the video):
![image](https://user-images.githubusercontent.com/39037141/61162379-96cf4c00-a508-11e9-8798-c3fbed8316da.png)

**Comment by owyn-outlands** [comment]
I have also noticed that our graphics/spelleffects in motion don't properly hue themself.
IE:  when we use bones to "fly" from a monster, they stay neutral hued, even though they have been assigned a hue.

**Comment by andreakarasho** [comment]
Should be fixed and patt of the isseu is well documented here https://github.com/andreakarasho/ClassicUO/issues/757

**Comment by BlackTeaOutlands** [comment]
This is not fixed. Animations are still not played properly. Example is still as above: Barbed Prowler (and for example Silicite) in Cavernam.

**Comment by andreakarasho** [comment]
effects should be fixed. 
Probably corpse graphic too. If it is not, open another issue
