### ISSUE TITLE
Using Organizer Agent after manually dropping items, creates leftover ghosted items

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#598]
I'm not quite sure exactly how to reproduce it consistently, but it happens a fair  deal. If you drop an item (in this case a stack of gold) on a chest, you can even wait for the sound to confirm that the stack was dropped, then hit an organizer agent, then it will often produce a ghosted version of the item you dropped manually at the previous location. Sometimes this item will be selectable, and will bounce back and keep appearing even if you close the container, somtimes it will vanish when you drag it once or when you open and close the container.

Example in the video below, where I first drop a gold stack manually which then reappears ghosted when I start the organize agent:
https://imgur.com/2q61k4v

**Comment by andreakarasho** [comment]
News? [i close it until i receive any news]

**Comment by BlackTeaOutlands** [comment]
Still the same issue. If it wasn't fixed, then why would it not still be an issue? :P Why news?

**Comment by andreakarasho** [comment]
Because lot of code has been changed and some issue might been fixed

**Comment by andreakarasho** [comment]
if you run Razor with standard client, does it happen?

**Comment by andreakarasho** [comment]
I pushed a patch about ghost itmes. 
I close it until feedbacks

**Comment by BlackTeaOutlands** [comment]
It's not fixed, at least not my issue.

It occurs specifically when using an Organizer agent, then it will pop back into existence the last item that you moved.

You can see it in the gif below at the end (the small bottle pops back into existence after I resupply from the shelf and start using the organizer macro).

https://imgur.com/Y7qbTes

**Comment by andreakarasho** [comment]
Seems the same of https://github.com/andreakarasho/ClassicUO/issues/994
