### ISSUE TITLE
Custom Housing teleporter/cost bug

### ISSUE THREAD

**Issue by Pumpk1ns** [ClassicUO/ClassicUO#891]
**Describe the bug**
The total cost of the custom house is not 100% right all the time.
The formula to calculate the cost seems to be the right but it need a small tweek to the way cuo adds teleporters.
When you place a teleporter (fixture) over the first floor (story 1), it should replaces the tile bellow. 
That means you are not adding a new component, you are "replacing" that component floor tile with a fixture and the price should stay the same because all components/fixtures have the same price.

Bug: CUO is not removing house floor component when a teleporter is added on the 1 floor.

**To Reproduce**
1. Place a custom house.
2. Select a teleporter and place it on the first floor.
3. Check the total cost, check the total components/fixture.

**Expected behavior**
When you add a teleporter at the first floor you are actualy replacing the foundament dirt floor tile (component) with a teleporter (fixture).
You should see -1 house components + 1 house fixture.

**Screenshots**
Original Client:
![cuobug](https://user-images.githubusercontent.com/46279173/71763880-8c9f7080-2ee1-11ea-94fd-fcd4e2a3af2b.gif)
CUO:
![cuobug2](https://user-images.githubusercontent.com/46279173/71763884-95904200-2ee1-11ea-93a1-9dcc2851b5cf.gif)

More examples:

Watch careful the behaviour of the numbers when teleporters are placed. 
https://youtu.be/RzO0yL_pL6U?t=1399

You need to turn the speed of this video to 0.25 and watch in 480p. This video shows the same behavior.
https://youtu.be/iyFqSreQ4cM?t=19

**Desktop (please complete the following information):**
 - OS: win 10
 - Emulator: https://www.polserver.com
 - CUO: Latest dev
 - UO Client: 7.0.83.27

**Comment by andreakarasho** [comment]
should be fixed

**Comment by Pumpk1ns** [comment]
The price seems to be right now.

Bug:
If you add a teleporter on the first floor, the gump should show : -1 component  +1 fixture.
(Because you removed 1 component and add instead a fixture.)
If you add a teleporter on the second floor, the gump should show: just +1 fixture. 
(Because you added a new fixture but didnt remove anything.)

Every custom house has a limit for fixtures. if you add the total of fixture the number turns red.
At the moment you can add infinite fixtures.
![tele](https://user-images.githubusercontent.com/46279173/71768870-c9d42480-2f1a-11ea-9389-2dcdab999086.png)

Check the gifs to see how it works.

**Comment by andreakarasho** [comment]
pushed a fix, let me know

**Comment by Pumpk1ns** [comment]
The limit of fixtures seems to be working now.

The door is a fixture too but it works little different, when you add it, you dont need to remove the floor like with teleporters
When you add a door you just add +1 fixture, the total of components stays the same.


![1be2ebefd693551bb14d96867a7925e6](https://user-images.githubusercontent.com/46279173/71778658-da36de80-2fb0-11ea-9d7f-770331a222be.png)

**Comment by Pumpk1ns** [comment]
On the original client:
When an item cant be placed it turns red.
When you can place an item the floor turns yellow.
When you select the erase tool and point over an editable item it turns red.

![color](https://user-images.githubusercontent.com/46279173/71778778-757c8380-2fb2-11ea-9276-8e14fd015a83.gif)

**Comment by Pumpk1ns** [comment]
Bug #1: Before placing an item it is not 100% aligned to the spot you want to place the item, the height seems to be wrong.

Bug #2: On the original client you can hold the left mouse button and place multiple items while holding it.

**Comment by Pumpk1ns** [comment]
The text on the buttons inside the "System Menu" are normally in black and when you press they turn yellow.

Atm on CUO they are always yellow.

On original client:
![72fef16795386afd390420084f45f099](https://user-images.githubusercontent.com/46279173/71784613-87334a80-2ff5-11ea-8f36-dbb00ee045f4.png)

**Comment by andreakarasho** [comment]
bug 1 should be fixed

**Comment by andreakarasho** [comment]
request 2 done.

Can i mark this issue as done?

**Comment by Pumpk1ns** [comment]
Button colors are fine now, but the font is different. (nitpicking 😛 )
On the 2th floor the door still removing the floor item underneath it.

Placing an item still not 100% aligned to the spot you want to place.

**Comment by andreakarasho** [comment]
shuold be fine now

**Comment by andreakarasho** [comment]
i didn't test recently commits honestly. If something does not work i'll reopen the issue!
