### ISSUE TITLE
Ghosting Items

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#994]
Items will become ghosted under the following circumstance:

A) Drop item X on the ground
B) Move out of update range of X
C) Use an organizer agent on a chest to drop something from your backpack into the chest
D) X will reappear in your backpack as a ghosted item
E) This ghosted item can be removed graphically by moving it and then selecting something else, but an "invisible" item will remain which you can still grab.

**Comment by andreakarasho** [comment]
I followed your steps exactly, but i was not able to reproduce the issue in local.
I dropped a toolkit on the ground, moved out of the toolkit, run organizer1, nothing odd happened.

I tried with lastest Razor 1.6.4.2 and latest official cuo release and latest cuo dev release.

**Comment by BlackTeaOutlands** [comment]
Thanks for testing, if you add these steps then you will trigger the bug:


A) Turn off Object Delay in your settings (set to 0 seconds)

B) Make sure the Organizer List has enough items so that it will start Queueing items.

-- Possibly you don't need to do B)

**Comment by andreakarasho** [comment]
Still good on my side
![ySKmSIRGdd](https://user-images.githubusercontent.com/20810422/78460938-85952380-76c5-11ea-88ee-21343986d67b.gif)
![image](https://user-images.githubusercontent.com/20810422/78460945-8fb72200-76c5-11ea-8ccf-023b39664fe6.png)
![image](https://user-images.githubusercontent.com/20810422/78460949-9ba2e400-76c5-11ea-9520-57d9efe56425.png)

**Comment by BlackTeaOutlands** [comment]
Maybe you need the 500 ms forced object delay that Outlands server has. Looks like its immediately moving on your end. It seems to need to queue.

**Comment by roxya** [comment]
I can reproduce. Seems that after you place an item on the floor (manually), ItemHold is not cleared. And then in Black Tea's case, he is trying to organise too fast and gets a DenyMoveItem from Outlands. In this packet, the nonempty ItemHold item is created created in the last place it was picked up.

**Comment by andreakarasho** [comment]
Pushed a fix. Can you try in dev?

**Comment by roxya** [comment]
Still present in 0.1.3.429
![ghostitem](https://user-images.githubusercontent.com/7057924/78609414-8f9c5b00-785a-11ea-8725-08ce2f3197fc.gif)

**Comment by andreakarasho** [comment]
> Still present in 0.1.3.429
> ![ghostitem](https://user-images.githubusercontent.com/7057924/78609414-8f9c5b00-785a-11ea-8725-08ce2f3197fc.gif)

You organized mortar and dropped the arrow down.
For some reason the HoldItem replaces a mortar.
I pushed another fix. Again in Dev

**Comment by roxya** [comment]
Still the same.

To explain the GIF: The organiser did what it should, moved the mortar into a bag. The arrow was actually on the floor 20+ tiles away, not on my cursor and I had no other arrow. The arrow in my bag has the same serial as the arrow on the floor, and when I go into update range of the arrow on the floor, the "ghost" disappears from my pack.

An example fix (I don't know the implications), in the packet UpdateItemSA I did

```
if (ItemHold.Serial == serial && ItemHold.Dropped)
    ItemHold.Clear();
```

To stop the code in DenyMoveItem from creating the ghost from ItemHold.

**Comment by andreakarasho** [comment]
I tried to replicate the behaviour, but test server never denied a movement

**Comment by andreakarasho** [comment]
Fixed a wrong serial in that function and an inverted boolean, but I didn’t try honestly

**Comment by BlackTeaOutlands** [comment]
Still there on my end, same issue. Latest dev build.

Does your test server have the 500 ms forced server-side action delay that Outlands has?

**Comment by andreakarasho** [comment]
I reproduced the issue and @roxya was right.
Now should be ok

**Comment by BlackTeaOutlands** [comment]
Still one issue with ghosted items.
Drop resource map into a tome.
Use organizer agent (as described above).
Resource map will now be ghosted item.
This ghosted item is different though, you can't drag it or remove it any other way than close backpack.

See image.
https://imgur.com/QndTXjC

**Comment by andreakarasho** [comment]
fixed

**Comment by BlackTeaOutlands** [comment]
This issue is back since using launcher version of Outlands client.

**Comment by jaedan** [comment]
Outlands launcher is currently commit 9da963783dd174346d425de6eafee281719496b0

**Comment by andreakarasho** [comment]
https://github.com/andreakarasho/ClassicUO/blob/fa5a034e2a7679a1bdaac5f9f75eb4b52522c859/src/Network/PacketHandlers.cs#L4930
probably it's better to do ItemHold.Clear()

**Comment by SaschaKP** [comment]
this is also a problem in razor fixed here:
https://github.com/markdwags/Razor/commit/ca04d8deafdbbe999334aa8b5e57a2d299a3f406
and here:
https://github.com/markdwags/Razor/commit/9b67a0d5656c27d27a00e7b09d29cb097566a8f2

since the item remains into the dictionary when lift+dropped, so when you use organize, razor "thinks" that the item is near you, while it is not, leaving the itemhold full, the ghosted item and the inability to move that particular object (since every action moves in the dragdrop manager && actionqueue)

**Comment by SaschaKP** [comment]
maybe we should close this, if only related to razor? @andreakarasho

**Comment by andreakarasho** [comment]
Yes, after my latest commits i got few feedback and everything seems ok now.
